# About the Authors {-}

[*Dr. Alcalá Briseño*](https://github.com/ricardoi) class example structure. Presenting a class format for a class example on Network Analysis using Biophysical and Omics Data at the Your University in the United States. Systems methods need a revolutionary account for analyzing integrated spatial information and large-scale genomics data. We will use machine learning and network analysis to reveal patterns associated with spatial information with disease incidence and host distribution. We will use R Studio, and the terminal in the Computer Cluster at Your University. The class will be divided in two: concepts and practice. 

We will use R packages such as 
[**igraph**](https://R.org/packages/release/igraph)
[**geohabnet**](https://R.org/packages/release/geohabnet)
[**hoboR**](https://R.org/packages/release/hoboR)

In addition, they have played key roles in developing Impact Network Analysis (INA), Virome Network Analysis (ViNA), and genomic information processing pipeline [PP](http://nextflow.osu.edu/).

